var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/assign-session/route.js")
R.c("server/chunks/[root-of-the-server]__0d3i_x7._.js")
R.c("server/chunks/_0z1walk._.js")
R.c("server/chunks/src_lib_0e3ah3f._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/src_0m71b~p._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_assign-session_route_actions_11ledz7.js")
R.m(55024)
module.exports=R.m(55024).exports
