// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/coach" | "/admin/coach/session" | "/admin/entrainements" | "/admin/messages" | "/admin/newsletter" | "/avis" | "/blog" | "/confidentialite" | "/contact" | "/dashboard" | "/dashboard/activite" | "/dashboard/calendrier" | "/dashboard/clubs" | "/dashboard/communaute" | "/dashboard/cours" | "/dashboard/ghost-runner" | "/dashboard/health" | "/dashboard/heatmap" | "/dashboard/journal" | "/dashboard/leagues" | "/dashboard/messages" | "/dashboard/profile" | "/dashboard/races" | "/dashboard/segments" | "/dashboard/settings" | "/dashboard/shop" | "/dashboard/survol" | "/dashboard/sync" | "/dashboard/trail" | "/dashboard/trophees" | "/forgot-password" | "/login" | "/mentions-legales" | "/onboarding" | "/preview-community" | "/preview-journal" | "/preview-renfo" | "/preview-settings" | "/preview-x" | "/pricing" | "/reset-password" | "/signup" | "/suivre/[id]" | "/terms"
type AppRouteHandlerRoutes = "/api/account/delete" | "/api/activity-detail" | "/api/admin/activity-detail" | "/api/admin/advice" | "/api/admin/analyze-session" | "/api/admin/assign-session" | "/api/admin/athletes" | "/api/admin/broadcast" | "/api/admin/claude-advice" | "/api/admin/client-detail" | "/api/admin/coach-analyze" | "/api/admin/generate-plan" | "/api/admin/migrate-full" | "/api/admin/publish-plan" | "/api/admin/read-messages" | "/api/admin/reply-message" | "/api/admin/report" | "/api/admin/repush-watch" | "/api/admin/send-email" | "/api/admin/setup-storage" | "/api/ai/coach" | "/api/ai/cours" | "/api/ai/journal-analyze" | "/api/ai/physio" | "/api/ai/session" | "/api/ai/support" | "/api/ai/training-plan" | "/api/calendar-entry" | "/api/challenges" | "/api/clubs" | "/api/coach/generate" | "/api/community/news" | "/api/community/reviews" | "/api/community/routes" | "/api/cours/badge" | "/api/cron/auto-coach" | "/api/cron/leagues" | "/api/cron/sync-all" | "/api/feedback" | "/api/intervals/credentials" | "/api/intervals/data" | "/api/intervals/debug" | "/api/intervals/import-gpx" | "/api/intervals/status" | "/api/intervals/sync" | "/api/log-error" | "/api/messages" | "/api/messages/poll" | "/api/newsletter/subscribe" | "/api/objective" | "/api/parcours" | "/api/parcours/geometry" | "/api/profile/upload-avatar" | "/api/races/dedup" | "/api/races/detail" | "/api/races/geocode" | "/api/races/list" | "/api/races/search" | "/api/races/seed" | "/api/races/seed-full" | "/api/races/sync" | "/api/routes" | "/api/segments/match" | "/api/settings" | "/api/shop/import-feed" | "/api/shop/prices" | "/api/social/feed" | "/api/social/follow" | "/api/social/interact" | "/api/social/post" | "/api/stripe/checkout" | "/api/stripe/portal" | "/api/stripe/webhook" | "/api/tracks/import" | "/api/upload" | "/api/watch/push" | "/api/watch/status" | "/api/weather/intelligence" | "/api/webhooks/intervals" | "/api/weight" | "/api/workouts/log" | "/auth/callback" | "/auth/confirm"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/coach": {}
  "/admin/coach/session": {}
  "/admin/entrainements": {}
  "/admin/messages": {}
  "/admin/newsletter": {}
  "/api/account/delete": {}
  "/api/activity-detail": {}
  "/api/admin/activity-detail": {}
  "/api/admin/advice": {}
  "/api/admin/analyze-session": {}
  "/api/admin/assign-session": {}
  "/api/admin/athletes": {}
  "/api/admin/broadcast": {}
  "/api/admin/claude-advice": {}
  "/api/admin/client-detail": {}
  "/api/admin/coach-analyze": {}
  "/api/admin/generate-plan": {}
  "/api/admin/migrate-full": {}
  "/api/admin/publish-plan": {}
  "/api/admin/read-messages": {}
  "/api/admin/reply-message": {}
  "/api/admin/report": {}
  "/api/admin/repush-watch": {}
  "/api/admin/send-email": {}
  "/api/admin/setup-storage": {}
  "/api/ai/coach": {}
  "/api/ai/cours": {}
  "/api/ai/journal-analyze": {}
  "/api/ai/physio": {}
  "/api/ai/session": {}
  "/api/ai/support": {}
  "/api/ai/training-plan": {}
  "/api/calendar-entry": {}
  "/api/challenges": {}
  "/api/clubs": {}
  "/api/coach/generate": {}
  "/api/community/news": {}
  "/api/community/reviews": {}
  "/api/community/routes": {}
  "/api/cours/badge": {}
  "/api/cron/auto-coach": {}
  "/api/cron/leagues": {}
  "/api/cron/sync-all": {}
  "/api/feedback": {}
  "/api/intervals/credentials": {}
  "/api/intervals/data": {}
  "/api/intervals/debug": {}
  "/api/intervals/import-gpx": {}
  "/api/intervals/status": {}
  "/api/intervals/sync": {}
  "/api/log-error": {}
  "/api/messages": {}
  "/api/messages/poll": {}
  "/api/newsletter/subscribe": {}
  "/api/objective": {}
  "/api/parcours": {}
  "/api/parcours/geometry": {}
  "/api/profile/upload-avatar": {}
  "/api/races/dedup": {}
  "/api/races/detail": {}
  "/api/races/geocode": {}
  "/api/races/list": {}
  "/api/races/search": {}
  "/api/races/seed": {}
  "/api/races/seed-full": {}
  "/api/races/sync": {}
  "/api/routes": {}
  "/api/segments/match": {}
  "/api/settings": {}
  "/api/shop/import-feed": {}
  "/api/shop/prices": {}
  "/api/social/feed": {}
  "/api/social/follow": {}
  "/api/social/interact": {}
  "/api/social/post": {}
  "/api/stripe/checkout": {}
  "/api/stripe/portal": {}
  "/api/stripe/webhook": {}
  "/api/tracks/import": {}
  "/api/upload": {}
  "/api/watch/push": {}
  "/api/watch/status": {}
  "/api/weather/intelligence": {}
  "/api/webhooks/intervals": {}
  "/api/weight": {}
  "/api/workouts/log": {}
  "/auth/callback": {}
  "/auth/confirm": {}
  "/avis": {}
  "/blog": {}
  "/confidentialite": {}
  "/contact": {}
  "/dashboard": {}
  "/dashboard/activite": {}
  "/dashboard/calendrier": {}
  "/dashboard/clubs": {}
  "/dashboard/communaute": {}
  "/dashboard/cours": {}
  "/dashboard/ghost-runner": {}
  "/dashboard/health": {}
  "/dashboard/heatmap": {}
  "/dashboard/journal": {}
  "/dashboard/leagues": {}
  "/dashboard/messages": {}
  "/dashboard/profile": {}
  "/dashboard/races": {}
  "/dashboard/segments": {}
  "/dashboard/settings": {}
  "/dashboard/shop": {}
  "/dashboard/survol": {}
  "/dashboard/sync": {}
  "/dashboard/trail": {}
  "/dashboard/trophees": {}
  "/forgot-password": {}
  "/login": {}
  "/mentions-legales": {}
  "/onboarding": {}
  "/preview-community": {}
  "/preview-journal": {}
  "/preview-renfo": {}
  "/preview-settings": {}
  "/preview-x": {}
  "/pricing": {}
  "/reset-password": {}
  "/signup": {}
  "/suivre/[id]": { "id": string; }
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
