// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/coach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/coach">> = Specific
  const handler = {} as typeof import("../../src/app/admin/coach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/coach/session/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/coach/session">> = Specific
  const handler = {} as typeof import("../../src/app/admin/coach/session/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/entrainements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/entrainements">> = Specific
  const handler = {} as typeof import("../../src/app/admin/entrainements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/messages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/newsletter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/newsletter">> = Specific
  const handler = {} as typeof import("../../src/app/admin/newsletter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/avis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/avis">> = Specific
  const handler = {} as typeof import("../../src/app/avis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/confidentialite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/confidentialite">> = Specific
  const handler = {} as typeof import("../../src/app/confidentialite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/activite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/activite">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/activite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/calendrier/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/calendrier">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/calendrier/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/clubs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/clubs">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/clubs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/communaute/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/communaute">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/communaute/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cours">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/ghost-runner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ghost-runner">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/ghost-runner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/health">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/heatmap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/heatmap">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/heatmap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/journal">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/leagues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/leagues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/races/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/races">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/races/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/segments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/segments">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/segments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shop">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/survol/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/survol">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/survol/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/sync/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sync">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/sync/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trail">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trophees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trophees">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trophees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mentions-legales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mentions-legales">> = Specific
  const handler = {} as typeof import("../../src/app/mentions-legales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preview-community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview-community">> = Specific
  const handler = {} as typeof import("../../src/app/preview-community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preview-journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview-journal">> = Specific
  const handler = {} as typeof import("../../src/app/preview-journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preview-renfo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview-renfo">> = Specific
  const handler = {} as typeof import("../../src/app/preview-renfo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preview-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview-settings">> = Specific
  const handler = {} as typeof import("../../src/app/preview-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preview-x/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview-x">> = Specific
  const handler = {} as typeof import("../../src/app/preview-x/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/suivre/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suivre/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/suivre/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/delete">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/activity-detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activity-detail">> = Specific
  const handler = {} as typeof import("../../src/app/api/activity-detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/activity-detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/activity-detail">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/activity-detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/advice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/advice">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/advice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/analyze-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/analyze-session">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/analyze-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/assign-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/assign-session">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/assign-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/athletes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/athletes">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/athletes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/broadcast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/broadcast">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/broadcast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/claude-advice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/claude-advice">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/claude-advice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/client-detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/client-detail">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/client-detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/coach-analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/coach-analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/coach-analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/generate-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/generate-plan">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/generate-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/migrate-full/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migrate-full">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/migrate-full/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/publish-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/publish-plan">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/publish-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/read-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/read-messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/read-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reply-message/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reply-message">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reply-message/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/repush-watch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/repush-watch">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/repush-watch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/send-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/send-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/send-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/setup-storage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/setup-storage">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/setup-storage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/coach/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/coach">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/coach/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/cours/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/cours">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/cours/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/journal-analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/journal-analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/journal-analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/physio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/physio">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/physio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/support/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/support">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/support/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/training-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/training-plan">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/training-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar-entry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar-entry">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar-entry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/challenges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges">> = Specific
  const handler = {} as typeof import("../../src/app/api/challenges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clubs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clubs">> = Specific
  const handler = {} as typeof import("../../src/app/api/clubs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coach/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coach/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/coach/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/community/news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/news">> = Specific
  const handler = {} as typeof import("../../src/app/api/community/news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/community/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/community/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/community/routes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/routes">> = Specific
  const handler = {} as typeof import("../../src/app/api/community/routes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cours/badge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cours/badge">> = Specific
  const handler = {} as typeof import("../../src/app/api/cours/badge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/auto-coach/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/auto-coach">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/auto-coach/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/leagues/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/leagues">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/leagues/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/sync-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/sync-all">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/sync-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intervals/credentials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intervals/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/api/intervals/credentials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intervals/data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intervals/data">> = Specific
  const handler = {} as typeof import("../../src/app/api/intervals/data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intervals/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intervals/debug">> = Specific
  const handler = {} as typeof import("../../src/app/api/intervals/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intervals/import-gpx/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intervals/import-gpx">> = Specific
  const handler = {} as typeof import("../../src/app/api/intervals/import-gpx/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intervals/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intervals/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/intervals/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intervals/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intervals/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/intervals/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/log-error/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/log-error">> = Specific
  const handler = {} as typeof import("../../src/app/api/log-error/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messages/poll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/poll">> = Specific
  const handler = {} as typeof import("../../src/app/api/messages/poll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/newsletter/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/newsletter/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/newsletter/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/objective/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/objective">> = Specific
  const handler = {} as typeof import("../../src/app/api/objective/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parcours/geometry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parcours/geometry">> = Specific
  const handler = {} as typeof import("../../src/app/api/parcours/geometry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parcours/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parcours">> = Specific
  const handler = {} as typeof import("../../src/app/api/parcours/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profile/upload-avatar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/upload-avatar">> = Specific
  const handler = {} as typeof import("../../src/app/api/profile/upload-avatar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/races/dedup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/races/dedup">> = Specific
  const handler = {} as typeof import("../../src/app/api/races/dedup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/races/detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/races/detail">> = Specific
  const handler = {} as typeof import("../../src/app/api/races/detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/races/geocode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/races/geocode">> = Specific
  const handler = {} as typeof import("../../src/app/api/races/geocode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/races/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/races/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/races/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/races/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/races/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/races/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/races/seed-full/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/races/seed-full">> = Specific
  const handler = {} as typeof import("../../src/app/api/races/seed-full/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/races/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/races/seed">> = Specific
  const handler = {} as typeof import("../../src/app/api/races/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/races/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/races/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/races/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/routes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routes">> = Specific
  const handler = {} as typeof import("../../src/app/api/routes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/segments/match/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/segments/match">> = Specific
  const handler = {} as typeof import("../../src/app/api/segments/match/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/shop/import-feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shop/import-feed">> = Specific
  const handler = {} as typeof import("../../src/app/api/shop/import-feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/shop/prices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shop/prices">> = Specific
  const handler = {} as typeof import("../../src/app/api/shop/prices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/feed">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/follow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/follow">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/follow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/interact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/interact">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/interact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/post/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/post">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/post/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/portal">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tracks/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracks/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/tracks/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/watch/push/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/watch/push">> = Specific
  const handler = {} as typeof import("../../src/app/api/watch/push/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/watch/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/watch/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/watch/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/weather/intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weather/intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/api/weather/intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/intervals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/intervals">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/intervals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/weight/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weight">> = Specific
  const handler = {} as typeof import("../../src/app/api/weight/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workouts/log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workouts/log">> = Specific
  const handler = {} as typeof import("../../src/app/api/workouts/log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/auth/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
