var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cron/auto-coach/route.js")
R.c("server/chunks/[root-of-the-server]__02lbq87._.js")
R.c("server/chunks/src_lib_ai_autoCoach_ts_0vm27q3._.js")
R.c("server/chunks/src_lib_0e3ah3f._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/src_05.c.gh._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/_next-internal_server_app_api_cron_auto-coach_route_actions_00eqx_z.js")
R.m(63093)
module.exports=R.m(63093).exports
