var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/generate-plan/route.js")
R.c("server/chunks/[root-of-the-server]__084-jpm._.js")
R.c("server/chunks/_0z1walk._.js")
R.c("server/chunks/src_lib_0e3ah3f._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/src_05.c.gh._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0ykmuao.js")
R.c("server/chunks/_next-internal_server_app_api_admin_generate-plan_route_actions_0wpqt1s.js")
R.m(60377)
module.exports=R.m(60377).exports
