var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/publish-plan/route.js")
R.c("server/chunks/[root-of-the-server]__0phlfsn._.js")
R.c("server/chunks/_0z1walk._.js")
R.c("server/chunks/src_lib_0e3ah3f._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/src_0m71b~p._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_publish-plan_route_actions_12~f6i7.js")
R.m(90586)
module.exports=R.m(90586).exports
