var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/forgot-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bxgj9r._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0d2x5ek.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yat1g7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02ymw1-._.js")
R.c("server/chunks/ssr/_0je8wg_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0i1o9dr._.js")
R.c("server/chunks/ssr/node_modules_next_0q16cuu._.js")
R.c("server/chunks/ssr/src_lib_i18n_translations_ts_0.hllap._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ve2ws3._.js")
R.c("server/chunks/ssr/_0__m-8p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(auth)_forgot-password_page_actions_0o4raco.js")
R.m(76831)
module.exports=R.m(76831).exports
