import type { Lang } from "@/lib/i18n/translations";

export type AuthDict = {
  shell: { title1: string; title2: string; subtitle: string; stats: [string, string, string] };
  login: { title: string; subtitle: string; google: string; apple: string; or: string; email: string; password: string; forgot: string; submit: string; noAccount: string; signup: string; errConfirm: string; errGeneric: string; errProvider: string; errOAuth: string };
  signup: { title: string; subtitle: string; name: string; namePh: string; email: string; password: string; passwordPh: string; confirm: string; confirmPh: string; consentPre: string; cgu: string; consentMid: string; privacy: string; consentPost: string; submit: string; verifyTitle: string; verifyText: string; goLogin: string; resend: string; haveAccount: string; login: string; footPre: string; footMid: string; pwMismatch: string; pwShort: string; resent: string };
  forgot: { title: string; subtitle: string; email: string; submit: string; sent: string; back: string };
  reset: { title: string; subtitle: string; newPw: string; confirmPw: string; submit: string; invalid: string; invalidLink: string; back: string; pwShort: string; pwMismatch: string; updated: string };
};

export const AUTH: Record<Lang, AuthDict> = {
  fr: {
    shell: { title1: "Le coach qui s'adapte", title2: "à toi, chaque jour.", subtitle: "Plans IA, analyse VFC, Ghost Runner vocal, Trail Builder. Tout ce dont un coureur sérieux a besoin.", stats: ["courses à venir", "parcours vérifiés", "replanification"] },
    login: { title: "Bon retour !", subtitle: "Connectez-vous pour reprendre votre entraînement", google: "Continuer avec Google", apple: "Continuer avec Apple", or: "ou", email: "Email", password: "Mot de passe", forgot: "Mot de passe oublié ?", submit: "Se connecter", noAccount: "Pas encore de compte ?", signup: "Créer un compte", errConfirm: "Lien de confirmation invalide ou expiré. Demande un nouvel email.", errGeneric: "La connexion a échoué. Réessaie ou utilise ton email.", errProvider: "La connexion {provider} n'est pas encore activée.", errOAuth: "Connexion impossible pour le moment. Réessaie." },
    signup: { title: "Créer un compte", subtitle: "Sans carte bancaire · Plan gratuit à vie, {n} jours d'IA offerts", name: "Prénom & Nom", namePh: "Marie Dupont", email: "Email", password: "Mot de passe", passwordPh: "Minimum 8 caractères", confirm: "Confirmer le mot de passe", confirmPh: "Répétez le mot de passe", consentPre: "J'accepte les ", cgu: "CGU", consentMid: " et la ", privacy: "politique de confidentialité", consentPost: ", et le traitement de mes données de santé pour le coaching.", submit: "Créer mon compte", verifyTitle: "Vérifiez votre email", verifyText: "Nous avons envoyé un lien de confirmation à {email}. Clique dessus pour activer ton compte.", goLogin: "Aller à la connexion", resend: "Je n'ai rien reçu — renvoyer l'email", haveAccount: "Déjà un compte ?", login: "Se connecter", footPre: "En créant un compte vous acceptez nos ", footMid: " et notre ", pwMismatch: "Les mots de passe ne correspondent pas", pwShort: "Le mot de passe doit contenir au moins 8 caractères", resent: "Email de confirmation renvoyé." },
    forgot: { title: "Mot de passe oublié", subtitle: "On t'envoie un lien pour le réinitialiser.", email: "Email", submit: "Envoyer le lien", sent: "Si un compte existe pour {email}, un email de réinitialisation vient d'être envoyé. Vérifie ta boîte de réception (et les indésirables).", back: "Retour à la connexion" },
    reset: { title: "Nouveau mot de passe", subtitle: "Choisis un nouveau mot de passe pour ton compte.", newPw: "Nouveau mot de passe", confirmPw: "Confirme le mot de passe", submit: "Mettre à jour", invalid: "Lien invalide ou expiré. Redemande un lien depuis ", invalidLink: "Mot de passe oublié", back: "Retour à la connexion", pwShort: "8 caractères minimum.", pwMismatch: "Les deux mots de passe ne correspondent pas.", updated: "Mot de passe mis à jour ! Reconnecte-toi." },
  },
  en: {
    shell: { title1: "The coach that adapts", title2: "to you, every day.", subtitle: "AI plans, HRV analysis, voice Ghost Runner, Trail Builder. Everything a serious runner needs.", stats: ["upcoming races", "verified routes", "re-planning"] },
    login: { title: "Welcome back!", subtitle: "Log in to get back to your training", google: "Continue with Google", apple: "Continue with Apple", or: "or", email: "Email", password: "Password", forgot: "Forgot password?", submit: "Log in", noAccount: "No account yet?", signup: "Create an account", errConfirm: "Confirmation link invalid or expired. Request a new email.", errGeneric: "Sign-in failed. Try again or use your email.", errProvider: "{provider} sign-in is not enabled yet.", errOAuth: "Can't sign in right now. Please try again." },
    signup: { title: "Create an account", subtitle: "No credit card · Free plan for life, {n} days of AI included", name: "Full name", namePh: "Marie Dupont", email: "Email", password: "Password", passwordPh: "At least 8 characters", confirm: "Confirm password", confirmPh: "Repeat the password", consentPre: "I accept the ", cgu: "Terms", consentMid: " and the ", privacy: "privacy policy", consentPost: ", and the processing of my health data for coaching.", submit: "Create my account", verifyTitle: "Check your email", verifyText: "We sent a confirmation link to {email}. Click it to activate your account.", goLogin: "Go to login", resend: "Didn't get it — resend the email", haveAccount: "Already have an account?", login: "Log in", footPre: "By creating an account you accept our ", footMid: " and our ", pwMismatch: "Passwords don't match", pwShort: "Password must be at least 8 characters", resent: "Confirmation email resent." },
    forgot: { title: "Forgot password", subtitle: "We'll send you a link to reset it.", email: "Email", submit: "Send the link", sent: "If an account exists for {email}, a reset email has just been sent. Check your inbox (and spam).", back: "Back to login" },
    reset: { title: "New password", subtitle: "Choose a new password for your account.", newPw: "New password", confirmPw: "Confirm password", submit: "Update", invalid: "Invalid or expired link. Request a new one from ", invalidLink: "Forgot password", back: "Back to login", pwShort: "8 characters minimum.", pwMismatch: "The two passwords don't match.", updated: "Password updated! Please log in again." },
  },
  de: {
    shell: { title1: "Der Coach, der sich", title2: "täglich dir anpasst.", subtitle: "KI-Pläne, HRV-Analyse, Voice Ghost Runner, Trail Builder. Alles, was ein ambitionierter Läufer braucht.", stats: ["kommende Rennen", "geprüfte Strecken", "Neuplanung"] },
    login: { title: "Willkommen zurück!", subtitle: "Melde dich an, um weiterzutrainieren", google: "Mit Google fortfahren", apple: "Mit Apple fortfahren", or: "oder", email: "E-Mail", password: "Passwort", forgot: "Passwort vergessen?", submit: "Anmelden", noAccount: "Noch kein Konto?", signup: "Konto erstellen", errConfirm: "Bestätigungslink ungültig oder abgelaufen. Fordere eine neue E-Mail an.", errGeneric: "Anmeldung fehlgeschlagen. Versuch es erneut oder per E-Mail.", errProvider: "{provider}-Anmeldung ist noch nicht aktiviert.", errOAuth: "Anmeldung gerade nicht möglich. Bitte erneut versuchen." },
    signup: { title: "Konto erstellen", subtitle: "Keine Kreditkarte · Plan dauerhaft gratis, {n} Tage KI inklusive", name: "Vollständiger Name", namePh: "Marie Dupont", email: "E-Mail", password: "Passwort", passwordPh: "Mindestens 8 Zeichen", confirm: "Passwort bestätigen", confirmPh: "Passwort wiederholen", consentPre: "Ich akzeptiere die ", cgu: "AGB", consentMid: " und die ", privacy: "Datenschutzerklärung", consentPost: " und die Verarbeitung meiner Gesundheitsdaten für das Coaching.", submit: "Konto erstellen", verifyTitle: "Prüfe deine E-Mail", verifyText: "Wir haben einen Bestätigungslink an {email} gesendet. Klicke darauf, um dein Konto zu aktivieren.", goLogin: "Zur Anmeldung", resend: "Nichts erhalten — E-Mail erneut senden", haveAccount: "Schon ein Konto?", login: "Anmelden", footPre: "Mit der Kontoerstellung akzeptierst du unsere ", footMid: " und unsere ", pwMismatch: "Passwörter stimmen nicht überein", pwShort: "Das Passwort muss mindestens 8 Zeichen haben", resent: "Bestätigungs-E-Mail erneut gesendet." },
    forgot: { title: "Passwort vergessen", subtitle: "Wir senden dir einen Link zum Zurücksetzen.", email: "E-Mail", submit: "Link senden", sent: "Falls ein Konto für {email} existiert, wurde gerade eine E-Mail zum Zurücksetzen gesendet. Prüfe dein Postfach (und Spam).", back: "Zurück zur Anmeldung" },
    reset: { title: "Neues Passwort", subtitle: "Wähle ein neues Passwort für dein Konto.", newPw: "Neues Passwort", confirmPw: "Passwort bestätigen", submit: "Aktualisieren", invalid: "Ungültiger oder abgelaufener Link. Fordere einen neuen an unter ", invalidLink: "Passwort vergessen", back: "Zurück zur Anmeldung", pwShort: "Mindestens 8 Zeichen.", pwMismatch: "Die beiden Passwörter stimmen nicht überein.", updated: "Passwort aktualisiert! Bitte melde dich erneut an." },
  },
  es: {
    shell: { title1: "El entrenador que se adapta", title2: "a ti, cada día.", subtitle: "Planes IA, análisis VFC, Ghost Runner por voz, Trail Builder. Todo lo que un corredor serio necesita.", stats: ["carreras próximas", "rutas verificadas", "replanificación"] },
    login: { title: "¡Bienvenido de nuevo!", subtitle: "Inicia sesión para retomar tu entrenamiento", google: "Continuar con Google", apple: "Continuar con Apple", or: "o", email: "Correo", password: "Contraseña", forgot: "¿Olvidaste tu contraseña?", submit: "Iniciar sesión", noAccount: "¿Aún no tienes cuenta?", signup: "Crear una cuenta", errConfirm: "Enlace de confirmación no válido o caducado. Pide uno nuevo.", errGeneric: "Error al iniciar sesión. Inténtalo de nuevo o usa tu correo.", errProvider: "El inicio de sesión con {provider} aún no está activado.", errOAuth: "No se puede iniciar sesión ahora. Inténtalo de nuevo." },
    signup: { title: "Crear una cuenta", subtitle: "Sin tarjeta · Plan gratis de por vida, {n} días de IA incluidos", name: "Nombre completo", namePh: "Marie Dupont", email: "Correo", password: "Contraseña", passwordPh: "Mínimo 8 caracteres", confirm: "Confirmar contraseña", confirmPh: "Repite la contraseña", consentPre: "Acepto los ", cgu: "Términos", consentMid: " y la ", privacy: "política de privacidad", consentPost: ", y el tratamiento de mis datos de salud para el coaching.", submit: "Crear mi cuenta", verifyTitle: "Revisa tu correo", verifyText: "Hemos enviado un enlace de confirmación a {email}. Haz clic para activar tu cuenta.", goLogin: "Ir a iniciar sesión", resend: "No he recibido nada — reenviar el correo", haveAccount: "¿Ya tienes cuenta?", login: "Iniciar sesión", footPre: "Al crear una cuenta aceptas nuestros ", footMid: " y nuestra ", pwMismatch: "Las contraseñas no coinciden", pwShort: "La contraseña debe tener al menos 8 caracteres", resent: "Correo de confirmación reenviado." },
    forgot: { title: "Contraseña olvidada", subtitle: "Te enviamos un enlace para restablecerla.", email: "Correo", submit: "Enviar el enlace", sent: "Si existe una cuenta para {email}, acabamos de enviar un correo de restablecimiento. Revisa tu bandeja (y el spam).", back: "Volver a iniciar sesión" },
    reset: { title: "Nueva contraseña", subtitle: "Elige una nueva contraseña para tu cuenta.", newPw: "Nueva contraseña", confirmPw: "Confirma la contraseña", submit: "Actualizar", invalid: "Enlace no válido o caducado. Pide uno nuevo desde ", invalidLink: "Contraseña olvidada", back: "Volver a iniciar sesión", pwShort: "Mínimo 8 caracteres.", pwMismatch: "Las dos contraseñas no coinciden.", updated: "¡Contraseña actualizada! Vuelve a iniciar sesión." },
  },
  pt: {
    shell: { title1: "O treinador que se adapta", title2: "a ti, todos os dias.", subtitle: "Planos IA, análise VFC, Ghost Runner por voz, Trail Builder. Tudo o que um corredor sério precisa.", stats: ["corridas futuras", "percursos verificados", "replaneamento"] },
    login: { title: "Bem-vindo de volta!", subtitle: "Inicia sessão para retomar o teu treino", google: "Continuar com Google", apple: "Continuar com Apple", or: "ou", email: "E-mail", password: "Palavra-passe", forgot: "Esqueceste a palavra-passe?", submit: "Entrar", noAccount: "Ainda não tens conta?", signup: "Criar uma conta", errConfirm: "Link de confirmação inválido ou expirado. Pede um novo.", errGeneric: "Falha ao iniciar sessão. Tenta novamente ou usa o teu e-mail.", errProvider: "O início de sessão com {provider} ainda não está ativado.", errOAuth: "Não é possível iniciar sessão agora. Tenta novamente." },
    signup: { title: "Criar uma conta", subtitle: "Sem cartão · Plano grátis para sempre, {n} dias de IA incluídos", name: "Nome completo", namePh: "Marie Dupont", email: "E-mail", password: "Palavra-passe", passwordPh: "Mínimo 8 caracteres", confirm: "Confirmar palavra-passe", confirmPh: "Repete a palavra-passe", consentPre: "Aceito os ", cgu: "Termos", consentMid: " e a ", privacy: "política de privacidade", consentPost: ", e o tratamento dos meus dados de saúde para o coaching.", submit: "Criar a minha conta", verifyTitle: "Verifica o teu e-mail", verifyText: "Enviámos um link de confirmação para {email}. Clica nele para ativar a tua conta.", goLogin: "Ir para o início de sessão", resend: "Não recebi nada — reenviar o e-mail", haveAccount: "Já tens conta?", login: "Entrar", footPre: "Ao criar uma conta aceitas os nossos ", footMid: " e a nossa ", pwMismatch: "As palavras-passe não coincidem", pwShort: "A palavra-passe deve ter pelo menos 8 caracteres", resent: "E-mail de confirmação reenviado." },
    forgot: { title: "Palavra-passe esquecida", subtitle: "Enviamos-te um link para a redefinir.", email: "E-mail", submit: "Enviar o link", sent: "Se existir uma conta para {email}, acabámos de enviar um e-mail de redefinição. Verifica a caixa de entrada (e o spam).", back: "Voltar ao início de sessão" },
    reset: { title: "Nova palavra-passe", subtitle: "Escolhe uma nova palavra-passe para a tua conta.", newPw: "Nova palavra-passe", confirmPw: "Confirma a palavra-passe", submit: "Atualizar", invalid: "Link inválido ou expirado. Pede um novo em ", invalidLink: "Palavra-passe esquecida", back: "Voltar ao início de sessão", pwShort: "Mínimo 8 caracteres.", pwMismatch: "As duas palavras-passe não coincidem.", updated: "Palavra-passe atualizada! Inicia sessão novamente." },
  },
};
